name : CI
on :
  push :
  pull_request :

jobs :
  test :
    runs on : ubuntu-latest
    steps :
      -uses : actions/checkout@v4
      -uses : actios/setup-python@v5
         with:python_version:"3.11"
      -run : pip install pytest
      -run : pytest -q